server:
  port: 8000

spring:
  application:
    name: auth-service
  jackson:
    serialization:
      INDENT_OUTPUT: true
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/AUTH_SERVICE
      username: root
      password: password
      driver-class-name: com.mysql.jdbc.Driver