server:
  port: 8000
spring:
  application:
    name: auth-service
  jackson:
    serialization:
      INDENT_OUTPUT: true
  datasource:
    hikari:
      username: root
      password: root@root
    url: jdbc:mysql://localhost:3306/AUTH_SERVICE
    driver-class-name: com.mysql.jdbc.Driver
  flyway:
    locations: classpath:db/migration
sec:
    key-alias: auth
    key-store: auth.jks
    key-password: password
logging:
  file: auth-service.log
  pattern:
    dateformat: YYYY-MM-DD
  level:
    root: info